/**
 * Axiom Hive Technology — Project attribution: Alexis M. Adams and Nicholas Michael Grossi.
 * Research assistance: Manus AI. Attribution does not determine ownership or rights.
 */

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { LockKeyhole, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Administration() {
  const utils = trpc.useUtils();
  const projects = trpc.governance.projects.list.useQuery();
  const [projectId, setProjectId] = useState("");
  const [name, setName] = useState("Controlled drafting baseline");
  const [version, setVersion] = useState("v0.2");
  const [memberUserId, setMemberUserId] = useState("");
  const [memberRole, setMemberRole] = useState<"author" | "reviewer" | "admin">("author");
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0].id); }, [projects.data, projectId]);
  const policies = trpc.governance.administration.policies.useQuery({ projectId }, { enabled: Boolean(projectId) });
  const members = trpc.governance.projects.members.useQuery({ projectId }, { enabled: Boolean(projectId) });
  const create = trpc.governance.administration.createPolicy.useMutation({ onSuccess: async () => { await utils.governance.administration.policies.invalidate({ projectId }); toast.success("Policy version recorded."); }, onError: error => toast.error(error.message) });
  const addMember = trpc.governance.projects.addMember.useMutation({ onSuccess: async () => { await utils.governance.projects.members.invalidate({ projectId }); setMemberUserId(""); toast.success("Workspace membership and role assignment recorded."); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-5xl space-y-7">
    <section className="rounded-3xl bg-[#16372c] p-7 text-white md:p-9"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-xl bg-emerald-200 text-emerald-950"><Settings2 className="size-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-200/75">Administrator controls</p><h1 className="mt-2 font-serif text-4xl">Policy versions and access boundaries.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-emerald-50/70">Administrative operations are restricted by a server-side workspace-role check. The interface does not substitute for the protected authorization decision.</p></div></div></section>
    <section className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><div className="space-y-6"><form onSubmit={event => { event.preventDefault(); create.mutate({ projectId, name, version }); }} className="rounded-2xl border border-[#dce3dc] bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><LockKeyhole className="size-5 text-emerald-800" /><h2 className="font-serif text-xl">Create policy version</h2></div><label className="mt-5 block text-xs font-semibold uppercase tracking-[0.12em] text-[#56645c]">Workspace<select value={projectId} onChange={event => setProjectId(event.target.value)} className="mt-2 h-10 w-full rounded-md border border-input bg-white px-3 text-sm">{projects.data?.filter(project => project.workspaceRole === "admin").map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="mt-4 block text-xs font-semibold uppercase tracking-[0.12em] text-[#56645c]">Policy name<Input value={name} onChange={event => setName(event.target.value)} className="mt-2" required /></label><label className="mt-4 block text-xs font-semibold uppercase tracking-[0.12em] text-[#56645c]">Version<Input value={version} onChange={event => setVersion(event.target.value)} className="mt-2" required /></label><Button disabled={create.isPending || !projectId} className="mt-5 w-full bg-[#16372c] hover:bg-[#204a3a]">{create.isPending ? "Recording version…" : "Record policy version"}</Button></form>
      <form onSubmit={event => { event.preventDefault(); const userId = Number(memberUserId); if (!Number.isInteger(userId) || userId < 1) return toast.error("Provide a valid authenticated account numeric ID."); addMember.mutate({ projectId, userId, role: memberRole }); }} className="rounded-2xl border border-[#dce3dc] bg-white p-6 shadow-sm"><h2 className="font-serif text-xl">Assign or reassign workspace role</h2><p className="mt-2 text-sm leading-5 text-[#66746c]">Only an administrator can create, view, or reassign workspace memberships. The procedure updates an existing member instead of creating a duplicate record.</p><label className="mt-4 block text-xs font-semibold uppercase tracking-[0.12em] text-[#56645c]">Authenticated account ID<Input value={memberUserId} onChange={event => setMemberUserId(event.target.value)} className="mt-2" inputMode="numeric" placeholder="e.g., 42" required /></label><label className="mt-4 block text-xs font-semibold uppercase tracking-[0.12em] text-[#56645c]">Workspace role<select value={memberRole} onChange={event => setMemberRole(event.target.value as typeof memberRole)} className="mt-2 h-10 w-full rounded-md border border-input bg-white px-3 text-sm"><option value="author">Author</option><option value="reviewer">Reviewer</option><option value="admin">Administrator</option></select></label><Button disabled={addMember.isPending || !projectId} className="mt-5 w-full bg-[#16372c] hover:bg-[#204a3a]">{addMember.isPending ? "Recording role…" : "Record workspace role"}</Button></form></div>
      <div className="space-y-6"><section className="rounded-2xl border border-[#dce3dc] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-serif text-xl">Recorded policy versions</h2><Badge variant="outline">{policies.data?.length ?? 0} entries</Badge></div><div className="mt-5 divide-y divide-[#e5eae5]">{policies.isLoading ? <p className="py-8 text-sm text-[#66746c]">Loading policy records…</p> : policies.data?.map(policy => <article key={policy.id} className="py-4 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-[#1d2a23]">{policy.name}</p><Badge className="bg-emerald-100 text-emerald-900 hover:bg-emerald-100">{policy.version}</Badge></div><p className="mt-2 text-xs leading-5 text-[#66746c]">Baseline controls: credential screening, reviewer approval before release, and no external tools.</p><p className="mt-2 text-[10px] uppercase tracking-[0.12em] text-[#7c8a82]">Created {policy.createdAt.toLocaleString()}</p></article>)}</div></section><section className="rounded-2xl border border-[#dce3dc] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-serif text-xl">Authorized workspace members</h2><Badge variant="outline">{members.data?.length ?? 0} members</Badge></div><div className="mt-4 divide-y divide-[#e5eae5]">{members.isLoading ? <p className="py-5 text-sm text-[#66746c]">Loading membership records…</p> : members.data?.map(member => <article key={member.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium text-[#1d2a23]">Account #{member.userId}</p><p className="mt-0.5 text-[10px] uppercase tracking-[0.12em] text-[#7c8a82]">Added {member.createdAt.toLocaleDateString()}</p></div><Badge className="bg-emerald-100 text-emerald-900 hover:bg-emerald-100">{member.role}</Badge></article>)}</div></section></div>
    </section>
  </div>;
}
